' 1.23 Incoming and outgoing messages, 
' PlantUML Language Reference Guide (V8037, pp. 16-17)
@startuml
[-> Bob
[o-> Bob
[o->o Bob
[x-> Bob
[<- Bob
[x<- Bob

Bob ->]
Bob ->o]
Bob o->o]
Bob ->x]

Bob <-]
Bob x<-]
@enduml
