' 2.4 Basic example, Drawing UML with PlantUML (V8037, p. 24)
@startuml
User -> (Start)
User --> (Use the application) : A small label
:Main Admin: ---> (Use the application) : This is\nyet another\nlabel
@enduml
