' 1.21 Lifeline Activation and Destruction, PlantUML Language Reference Guide (V8037, p. 15)
@startuml
participant User

User -> A: DoWork
activate A #FFBBBB

A -> A: Internal call
activate A #DarkSalmon

A -> B: <<createRequest>>
activate B

B --> A: RequestCreated
deactivate B
deactivate A
A -> User: Done
deactivate A

@enduml
