' 1.13 Notes on messages, PlantUML Language Reference Guide (V8037, p. 9)
@startuml
Alice ->Bob : hello
note left: this is a first note

Bob ->Alice : ok
note right: this is another note

Bob ->Bob : I am thinking
note left
    a note
    can also be defined
    on several lines
end note

@enduml
