' 3.18 Namespaces, PlantUML Language Reference Guide (V8037, pp. 44-45)
@startuml

class BaseClass

namespace net.dummy #DDDDDD {
    .BaseClass <|-- Person
    Meeting o-- Person

    .BaseClass <|- Meeting
}

namespace net.foo {
    net.dummy.Person <|- Person
    .BaseClass <|-- Person
    net.dummy.Meeting o-- Person
}

BaseClass <|-- net.unused.Person

@enduml
