' Figure A.5 The taxonomy of structure and behavior diagrams
' OMG, Unified Modeling Language 2.5, p. 683
@startuml

skinparam monochrome true
hide circle
hide members

abstract class "Diagram" as Diagram

abstract class "Structure\nDiagram" as StructureDiagram
abstract class "Behavior\nDiagram" as BehaviorDiagram

class "Profile\nDiagram" as ProfileDiagram
class "Class\nDiagram" as ClassDiagram
class "Composite\nStructure\nDiagram" as CompositeStructureDiagram
class "Component\nDiagram" as ComponentDiagram
class "Deployment\nDiagram" as DeploymentDiagram
class "Object\nDiagram" as ObjectDiagram
class "Package\nDiagram" as PackageDiagram

class "Activity\nDiagram" as ActivityDiagram
abstract class "Interaction\nDiagram" as InteractionDiagram
class "Use Case\nDiagram" as UseCaseDiagram
class "State Machine\nDiagram" as StateMachineDiagram

class "Sequence\nDiagram" as SequenceDiagram
class "Communication\nDiagram" as CommunicationDiagram
class "Interaction\nOverview\nDiagram" as InteractionOverviewDiagram
class "Timing\nDiagram" as TimingDiagram

Diagram <|-- StructureDiagram
Diagram <|-- BehaviorDiagram

StructureDiagram <|-- ProfileDiagram
StructureDiagram <|-- ClassDiagram
StructureDiagram <|-- CompositeStructureDiagram
StructureDiagram <|-- ComponentDiagram
StructureDiagram <|-- DeploymentDiagram
StructureDiagram <|-- ObjectDiagram
StructureDiagram <|-- PackageDiagram

BehaviorDiagram <|-- ActivityDiagram
BehaviorDiagram <|-- InteractionDiagram
BehaviorDiagram <|-- UseCaseDiagram
BehaviorDiagram <|-- StateMachineDiagram

InteractionDiagram <|-- SequenceDiagram
InteractionDiagram <|-- CommunicationDiagram
InteractionDiagram <|-- InteractionOverviewDiagram
InteractionDiagram <|-- TimingDiagram

@enduml
